// svelte/src/lib/components/PluginDetail.svelte
<script lang="ts">
  export let content: string | string[];
  export let title: string;

  let data: string[];
  $: data = content instanceof Array ? content : [content];
</script>

<style lang="scss">
  section:not(:last-child) {
    @apply mb-6;
  }
</style>

<section>
  <header>
    <h1>
      <strong>{title}</strong>
    </h1>
  </header>

  <ul class="list-none">
    {#each data as value}
      <li>{value}</li>
    {/each}
  </ul>
</section>

// react/src/components/PluginDetail.tsx
interface Props {
  content: string | string[];
  title: string;
}

export function PluginDetail({ content, title }: Props) {
  const data: string[] = content instanceof Array ? content : [content];

  return (
    <section tw="not-last:mb-6">
      <header>
        <h1>
          <strong>{title}</strong>
        </h1>
      </header>

      <ul tw="list-none">
        {data.map((value) => (
          <li key={value}>{value}</li>
        ))}
      </ul>
    </section>
  );
}
