// svelte/src/lib/components/SearchBar.svelte
<script lang="ts">
  import MdSearch from 'svelte-icons/md/MdSearch.svelte';
</script>

<!-- This is weird and hacky lol -->
<style lang="scss">
  :global(svg) {
    @apply ml-2;
    width: 20px !important;
  }
</style>

<form class="border-b-2 border-black flex items-center">
  <label for="plugin-search">Plugin Search</label>
  <input
    id="plugin-search"
    class="border-none bg-transparent outline-none flex flex-1"
  />
  <MdSearch />
</form>

// react/src/components/SearchBar.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { MdSearch } from 'react-icons/md';

export function SearchBar() {
  return (
    <form tw="border-b-2 border-black flex items-center">
      <label htmlFor="plugin-search">Plugin Search</label>
      <input
        id="plugin-search"
        tw="border-none bg-transparent outline-none flex flex-1"
      />
      <MdSearch tw="ml-2" />
    </form>
  );
}
